language: "en-US"
early_access: true

reviews:
  profile: "chill"
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: true
  auto_review:
    enabled: true
    drafts: false

chat:
  auto_reply: true

ignored_branch: "dev"
ignored_titles: "WIP, testing, prototype"

limit_reviews_by_label: "review-me"
path_filters: "*.js"

disable_poem: true
enable_beta_features: true
